#! /usr/bin/awk -f

# ignore the packets with sequence numnbers not in [low, high]
# Copyright (C) 2008,2017 Erik Auerswald <auerswald@fg-networking.de>
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# usage: ignore-sequence_numbers [-v low=NUMBER] [-v high=NUMBER] [FILE...]
# default interval is [0,0] (keep every packet)

BEGIN {
  if ((low == "") && (high == "")) {
    print "WARNING: Keeping every packet. Use -v low=L -v high=H to keep packets in [L,H]" > "/dev/stderr"
  }
}

/RECV/ {
  split($5, seq, />/)
  if ((seq[2] >= low) && ((high == "") || (seq[2] <= high))) {
    print
  }
}

!/RECV/ { print }
