#! /usr/bin/awk -f
/RECV/ {
  split($3, flow, />/)
  split($4, seq, />/)
  if (seq[2]>hist[flow[2]]) {
    print "packet " hist[flow[2]] " of flow " flow[2] " lost (or reordered)"
    hist[flow[2]]=seq[2]+1
  } else if (seq[2]<hist[flow[2]]) {
      print "packet " seq[2] " of flow " flow[2] " too late (or duplicated)"
  } else {
    hist[flow[2]]++
  }
}
